### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by KGergo88** [KGergo88/RDB_Monitor#39]
### Description
A few bigger changes were made in the project recently that are not yet described by the documentation, for example:
 - The project has now an established build process with QMake and Cmake
 - Coverage results can also be automatically generated with the **tests/test_coverage.py**. 
 - The settings for the serial ports are now editable
 - There is a GithubActions CI system with different jobs
 - The project got independent from the RDB Diplomaterv project

These points need to be documented in the README.md.

### Todo
Update the documentation with the:
- [x] Build instructions for the application (Linux + Windows)
- [x] Build instructions for the tests (Linux + Windows)
- [ ] ~~Steps to generate the coverage report~~ This is not needed as it is not something a common user would use
- [x] Describe the available CI jobs and their goals
- [x] User instructions for managing connections
